services:
  lab-portal:
    build: .
    container_name: lab-portal
    deploy:
      resources:
        limits:
          memory: 256M
    restart: always
    networks:
      - web-network
    environment:
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - ./app:/app/app
      - ./data:/app/data

networks:
  web-network:
    external: true
